name = "gvn-school-management"
pages_build_output_dir = ".vercel/output/static"

compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://lmsxjwcpjffqtgskfezm.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc3hqd2NwamZmcXRnc2tmZXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMDc4NjgsImV4cCI6MjEwMjU4Mzg2OH0.6IxD8UAuv32ajunENLG5x6deuRC3ee93WDv3av7eP3E"
